[functions.save_preview]
enabled = true
verify_jwt = false
import_map = "./functions/save_preview/deno.json"
entrypoint = "./functions/save_preview/index.ts"

[functions.preview_page]
enabled = true
verify_jwt = false
import_map = "./functions/preview_page/deno.json"
entrypoint = "./functions/preview_page/index.ts"

[functions.create_codesandbox]
enabled = true
verify_jwt = false
import_map = "./functions/create_codesandbox/deno.json"
entrypoint = "./functions/create_codesandbox/index.ts"
